version: "3"
services:
  azure-vote-back:
    image: redis:6.0.8
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"

  azure-vote-front:
    build: ./azure-vote
    image: azure-vote-front:v2.0.0
    container_name: azure-vote-front
    environment:
      REDIS: azure-vote-back
    ports:
      - "8080:80"

networks:
  default:
    driver: bridge
